1. Consulta de Vendedores

SELECT ID_VENDEDOR, NOME, SALARIO
FROM VENDEDORES
WHERE INATIVO = FALSE
ORDER BY NOME ASC;


2. Funcionários com Salário Acima da Média

SELECT 
    ID_VENDEDOR AS id, 
    NOME AS nome, 
    SALARIO AS salario
FROM VENDEDORES
WHERE SALARIO > (SELECT AVG(SALARIO) FROM VENDEDORES)
ORDER BY SALARIO DESC;


3. Resumo por cliente

SELECT 
    C.ID_CLIENTE, 
    C.RAZAO_SOCIAL, 
COALESCE(SUM(P.VALOR_TOTAL), 0) AS TOTAL
FROM CLIENTES C
LEFT JOIN PEDIDO P ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.ID_CLIENTE, C.RAZAO_SOCIAL
ORDER BY TOTAL DESC;


4. Situação por pedido

SELECT 
	D_PEDIDO AS ID, 
    VALOR_TOTAL AS VALOR,
    DATA_EMISSAO AS DATA, 
    CASE 
        WHEN DATA_CANCELAMENTO IS NOT NULL THEN 'CANCELADO'
        WHEN DATA_FATURAMENTO IS NOT NULL THEN 'FATURADO'
        ELSE 'PENDENTE'
    END AS SITUACAO 
FROM PEDIDO 
ORDER BY ID;


5. Produtos mais vendidos

SELECT 
P.ID_PRODUTO,
    SUM(ITP.QUANTIDADE) AS QUANTIDADE_VENDIDA,
    SUM(ITP.QUANTIDADE * ITP.PRECO_PRATICADO) AS TOTAL_VENDIDO,
    COUNT(DISTINCT ITP.ID_PEDIDO) AS PEDIDOS,
    COUNT(DISTINCT PE.ID_CLIENTE) AS CLIENTES
FROM ITENS_PEDIDO ITP
JOIN PRODUTOS P ON P.ID_PRODUTO = ITP.ID_PRODUTO
JOIN PEDIDO PE ON PE.ID_PEDIDO = ITP.ID_PEDIDO
GROUP BY P.ID_PRODUTO
ORDER BY QUANTIDADE_VENDIDA DESC, TOTAL_VENDIDO DESC
LIMIT 1;
